### PR TITLE
Allow repository names to be keywords or symbols or whatever.

### PR DESCRIPTION
**Pull request by technomancy**
This makes it so that `lein change repositories:private dissoc :passphrase` can work.

### CODE REVIEW

**Comment by technomancy** [comment]
I could be convinced that calling `name` on the id rather than `str` is a better choice, because it will only work on strings, keywords, and symbols IIRC; a bit less wild-west than "anything goes".

**Comment by technomancy** [comment]
You know what, I'm going to go ahead and make that switch so it uses `name` because it sounds a lot safer.

**Comment by technomancy** [comment]
The reason this is failing is that the tests have some cases where the `id` for a repository is nil. I can change the implementation to simply propagate nil values thru to the underlying Maven methods, but it seems like allowing a nil repository ID is not a great idea to begin with?

**Comment by cemerick** [comment]
Confused by the history here; you said there are failing tests, but I don't see them (now), and I'm not clear on whether the patch is now as you'd like it / as we discussed on irc?

**Comment by technomancy** [comment]
Sorry; I did a force push, so the history doesn't match the comments--I thought I updated the comments, but it looks like that didn't happen. Basically what happened is that while the `id` for *repositories* should always be set, the `make-repository` function is used internally to construct *mirrors* as well, and mirrors with a nil identifier are A-OK apparently. So we allow nil or any `name`-able thing now.

**Comment by cemerick** [comment]
Got it. This would have probably been apparent had I been paying more attention. Thanks!

**Comment by roanosullivan** [comment]
O'Sullivan Roan James liked your email
Spark by Readdle

**Pull request merged**
