### PR TITLE
support maven `managedDependencies` - fixes #72

### LINKED ISSUE #72: Add support for "managed" dependencies in `resolve-dependencies`
In Maven, a parent pom can specify a section called `dependencyManagement`.  If this is specified, the versions of the dependencies listed in this section are used when resolving transitive dependencies.  It also allows you to specify dependencies in the main sections of the pom w/o specifying a version number for them.

Exposing this functionality through the pomegranate API would be useful for writing leiningen plugins.  In Aether, `managedDependencies` is exposed as an optional argument to the constructor for a `CollectRequest`.  `pomegranate`'s `resolve-dependencies*` is already using this constructor, so adding this support would be as simple as adding support for another optional argument, and using it to populate the argument to the `CollectRequest` constructor with this value instead of hard-coding it to `nil`.

### PR DESCRIPTION
**Pull request by cprice404**
This PR adds support for passing a vector of `:managed-dependencies` to `resolve-dependencies` and `resolve-dependencies*`.  This allows pomegranate to support maven's built-in capabilities for determining version numbers from a `managedDepencies` configuration, e.g. from a parent project.

This work is intended to help make it possible to provide better support for parent projects in leiningen.

### CODE REVIEW

**Comment by cprice404** [comment]
This is intended to provide the implementation for the feature described in #72 .

**Comment by cprice404** [comment]
@senior added tests, discovered that classifiers didn't work, fixed them.  :)

**Comment by senior** [comment]
@cprice404 looks good to me

**Comment by cprice404** [comment]
@senior thanks!

@cemerick any thoughts on consideration for merging this?

**Pull request merged**
